blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Questions / Discussions
    url: https://github.com/xinglixing/gitkraken-ish/discussions
    about: Please ask and answer questions here.
  - name: ðŸ”’ Security report
    url: https://github.com/xinglixing/gitkraken-ish/security/policy
    about: Please report security issues here.
